---
- name: Install common applications
  apt:
    name: "{{ item }}"
    state: installed
    update_cache: yes
    cache_valid_time: 3600
  with_items: "{{common_apps}}"
  become: yes

- name: Select Vim alternative
  alternatives: name=vim link=/usr/bin/vim path=/usr/bin/vim.gtk3
  become: yes
