---
- name: Install nginx
  apt:
    name: nginx
    state: installed
    update_cache: yes
    cache_valid_time: 3600
  become: yes
  when: ansible_distribution != 'MacOSX'

- name: Install nginx via brew
  homebrew:
    name: nginx
    state: present
  when: ansible_distribution == 'MacOSX'

- name: Copy nginx shortname config
  template:
    src: ../files/nginx-shortname-config
    dest: "{{ (ansible_distribution != 'MacOSX') | ternary('/etc/nginx/sites-available/shortnames', '/usr/local/etc/nginx/servers/shortnames') }}"
    backup: yes
  with_items: "{{shortname_aliases}}"

- name: Create symlink for nginx shortname in sites-enabled
  file:
    src: /etc/nginx/sites-available/shortnames
    dest: /etc/nginx/sites-enabled/shortnames
    state: link
    force: yes
  when: ansible_distribution != 'MacOSX'

- name: Add shortname mappings to /etc/hosts
  blockinfile:
    dest: /etc/hosts
    block: |
      {% for key, value in item.items()|sort %}
      127.0.0.1 {{value.shortnames}}
      {% endfor %}
    marker: "# {mark} ANSIBLE MANAGED SHORTNAMES"
    backup: yes
  become: yes
  with_items: "{{shortname_aliases}}"

- name: Start nginx if necessary
  service:
    name: nginx
    state: started
  when: ansible_distribution != 'MacOSX'

- name: Start nginx if necessary on Mac
  shell: 'nginx -s stop; nginx'
  when: ansible_distribution == 'MacOSX'

- name: Reload nginx config
  service:
    name: nginx
    state: reloaded
  when: ansible_distribution != 'MacOSX'

- name: Reload nginx config on Mac
  command: 'nginx -s reload'
  when: ansible_distribution == 'MacOSX'
