---
- name: Create symlinks to dotfiles
  file:
    src: "{{ dotfiles }}/{{ item.src }}"
    dest: "{{ ansible_env.HOME }}/{{ item.dest }}"
    state: link
    force: yes
  with_items: "{{symlinks}}"

- name: Check local config file existence
  stat: path={{ ansible_env.HOME }}/{{ item }}
  with_items: "{{localconf}}"
  register: localconf_stat

- name: Copy default config files
  copy:
    src: "{{ item.item }}"
    dest: "{{ ansible_env.HOME }}/{{ item.item }}"
  when: not item.stat.exists
  with_items: "{{localconf_stat.results}}"
